### ISSUE TITLE
The  consistency of coordinate

### ISSUE THREAD

**Issue by taufikxu** [SiyuanQi/human-centric-scene-synthesis#3]
Hi, all.

I found a problem that, for generating new samples, the translation matrix denote the X, Z, Y axis correspondingly. But when you determine whether object i is on j, you just use the third coordinate, i.e., translation(2) and size(2), which i think should denote the y-axis, rather than the z-axis.

It would be great if you could give us a detail explanation.

**Comment by SiyuanQi-zz** [comment]
Thanks for pointing this out. It seems to be a bug in the code and it is fixed. 
Fortunately, it does not affect the results much, since supporting relations depends more on the [next few lines](https://github.com/SiyuanQi/human-centric-scene-synthesis/blob/master/src/cpp/Room.cpp#L164-L173). This checks if the top-down bounding box of object i is inside the box of object j.
